# Generated by Django 3.2.15 on 2023-04-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0003_alter_post_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/actus')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/actus')),
            ],
        ),
        migrations.CreateModel(
            name='Mitmachen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/actus')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/actus')),
            ],
        ),
        migrations.CreateModel(
            name='Neuigkeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/actus')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/actus')),
            ],
        ),
    ]
