# Generated by Django 3.2 on 2022-08-10 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mksd', '0003_auto_20220810_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='mksd_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
