# Generated by Django 3.2.15 on 2023-04-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0004_live_mitmachen_neuigkeit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='live',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mitmachen',
            name='image',
        ),
        migrations.RemoveField(
            model_name='neuigkeit',
            name='image',
        ),
    ]
