# Generated by Django 3.2 on 2022-08-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0005_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippets',
            field=models.CharField(default='click the link', max_length=255),
        ),
    ]
