# Generated by Django 3.2.15 on 2023-04-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0005_auto_20230416_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/actus'),
        ),
        migrations.AddField(
            model_name='mitmachen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/actus'),
        ),
        migrations.AddField(
            model_name='neuigkeit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/actus'),
        ),
    ]
