# Generated by Django 3.2.15 on 2023-04-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0007_auto_20230416_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitmachen_index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/actus')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/actus')),
                ('mit_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='mitmachen',
            old_name='mit_date',
            new_name='post_date',
        ),
    ]
