# Generated by Django 3.2 on 2022-08-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0007_alter_post_snippets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='snippets',
            new_name='snippet',
        ),
    ]
