# Generated by Django 3.2.15 on 2023-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0008_auto_20230425_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='files/video'),
        ),
    ]
