# Generated by Django 3.2.15 on 2023-06-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0009_live_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='live_date',
            field=models.DateField(verbose_name='Live date'),
        ),
        migrations.AlterField(
            model_name='mitmachen_index',
            name='mit_date',
            field=models.DateField(verbose_name='Mit date'),
        ),
        migrations.AlterField(
            model_name='neuigkeit',
            name='neu_date',
            field=models.DateField(verbose_name='Neu date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(verbose_name='Post date'),
        ),
    ]
