# Generated by Django 3.2.15 on 2023-06-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0010_auto_20230602_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='live_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mitmachen_index',
            name='mit_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='neuigkeit',
            name='neu_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Neuigkeit_pk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/actus')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/actus')),
                ('neu_date', models.DateField(auto_now_add=True)),
                ('neu_pk', models.ManyToManyField(related_name='neu_pk', to='mksd.Neuigkeit')),
            ],
        ),
    ]
