# Generated by Django 4.1.2 on 2023-02-03 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='cat_images/'),
            preserve_default=False,
        ),
    ]
