# Generated by Django 3.2.15 on 2023-06-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0011_auto_20230603_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neuigkeit_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/actus')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/actus')),
                ('body', models.CharField(max_length=250)),
                ('neu_date', models.DateField(auto_now_add=True)),
                ('neu_pk', models.ManyToManyField(related_name='neu_pk', to='mksd.Neuigkeit')),
            ],
        ),
        migrations.DeleteModel(
            name='Neuigkeit_pk',
        ),
    ]
