# Generated by Django 3.2.15 on 2023-06-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0012_auto_20230603_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuigkeit_detail',
            name='neu_pk',
            field=models.ManyToManyField(related_name='neuigkeit', to='mksd.Neuigkeit'),
        ),
    ]
