# Generated by Django 3.2.15 on 2023-06-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0013_alter_neuigkeit_detail_neu_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neuigkeit_detail',
            old_name='neu_pk',
            new_name='neuigkeit',
        ),
    ]
