# Generated by Django 3.2.15 on 2023-06-04 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0014_rename_neu_pk_neuigkeit_detail_neuigkeit'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuigkeit',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Neuigkeit_detail',
        ),
    ]
