# Generated by Django 3.2.2 on 2023-04-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0014_auto_20230404_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/cat_event')),
            ],
        ),
    ]
