# Generated by Django 3.2.15 on 2023-06-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0015_auto_20230604_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuigkeit',
            name='neu_date',
            field=models.DateField(),
        ),
    ]
