# Generated by Django 3.2.15 on 2023-06-04 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0017_alter_neuigkeit_neu_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitmachen_index',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
