# Generated by Django 3.2.15 on 2023-06-05 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mksd', '0018_mitmachen_index_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='live',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
